### ISSUE TITLE
Socket trying to connect to local host , may be change host URL can fix

### ISSUE THREAD

**Issue by Jittojoyes98** [prerana1821/doodleboard#1]
![Uploading Screenshot from 2024-02-23 10-36-59.png…]()

**Comment by prerana1821** [comment]
Hey @Jittojoyes98,
The screenshot that you have uploaded is not working.
You can have a look at `app-with-server` branch if you want to work on the live collaboration feature.

**Comment by Jittojoyes98** [comment]
hey @prerana1821 ,  i would like to contribute to a project that you mentioned on twitter. Will you be able to follow me back so that i can dm you. Btw i forgot what was this issue actually
